[workspace]
changelog_update = false
git_release_enable = false
git_tag_enable = false
pr_branch_prefix = "release-plz-"
pr_labels = ["release"]
release_always = false
repo_url = "https://github.com/arkworks-rs/spongefish"
semver_check = false

[[package]]
name = "spongefish"
git_release_enable = true
git_tag_enable = true
git_tag_name = "v{{ version }}"
version_group = "workspace"

[[package]]
name = "spongefish-circuit"
version_group = "workspace"

[[package]]
name = "spongefish-derive"
version_group = "workspace"

[[package]]
name = "spongefish-pow"
version_group = "workspace"
